# Generated by Django 6.1 on 2026-09-13 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_billing_address_order_currency_and_more'),
        ('tenants', '0002_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_37fed6_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_shop_id_c267ca_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at', 'id'], name='order_user_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', '-created_at', 'id'], name='order_shop_created_id_idx'),
        ),
    ]
