# Generated by Django 6.1 on 2026-09-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='unique_provider_attempt_reference'),
        ),
    ]
