# Generated by Django 6.1 on 2026-09-04 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type'),
        ('orders', '0002_order_billing_address_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['order', 'status'], name='inventory_r_order_i_b21025_idx'),
        ),
    ]
