# Generated by Django 6.1 on 2026-09-13 04:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_enable_pg_trgm'),
        ('tenants', '0002_shop'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='brand_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['slug'], name='product_slug_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='product_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sku'], name='variant_sku_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='variant_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
