# Generated by Django 6.1 on 2026-09-13 05:07

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_brand_name_trgm_idx_and_more'),
        ('tenants', '0002_shop'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_slug_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_desc_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_sku_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_name_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='brand_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='product_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('slug'), name='gin_trgm_ops'), name='product_slug_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='product_desc_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('sku'), name='gin_trgm_ops'), name='variant_sku_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='variant_name_trgm_idx'),
        ),
    ]
