# Generated by Django 6.1 on 2026-09-13 05:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_brand_brand_name_trgm_idx_and_more'),
        ('tenants', '0002_shop'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='simple', weight='A'), '||', django.contrib.postgres.search.SearchVector('slug', config='simple', weight='B'), django.contrib.postgres.search.SearchConfig('simple')), '||', django.contrib.postgres.search.SearchVector('description', config='simple', weight='D'), django.contrib.postgres.search.SearchConfig('simple')), name='product_fts_search_idx'),
        ),
    ]
